# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 23:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('due_date', models.DateTimeField()),
                ('scorecards_published', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('max_extensions', models.PositiveSmallIntegerField(default=0)),
                ('accepting_submissions', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Autograder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('invocation', models.CharField(max_length=100)),
                ('archive', models.FileField(upload_to='autograders/')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=32)),
                ('course_number', models.CharField(max_length=16)),
                ('semester', models.CharField(max_length=32)),
                ('default_extensions', models.PositiveSmallIntegerField(default=0)),
                ('default_max_extensions', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('grader_posix_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=140)),
                ('message', models.TextField()),
                ('course', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Extension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial', models.PositiveSmallIntegerField(default=0)),
                ('remaining', models.PositiveSmallIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Scorecard',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyz0123456789', min_length=8, primary_key=True, serialize=False)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('is_done', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ScorecardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_template', to='core.Assignment')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_name', models.CharField(max_length=32)),
                ('courses_active', models.ManyToManyField(blank=True, related_name='students', to='core.Course')),
                ('courses_dropped', models.ManyToManyField(blank=True, related_name='dropped_students', to='core.Course')),
                ('courses_grading', models.ManyToManyField(blank=True, related_name='graders', to='core.Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('latest_version', models.PositiveSmallIntegerField(default=0)),
                ('path', models.CharField(max_length=100)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.Assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='core.Student')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='scorecard',
            name='grader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scorecards_graded', to='core.Student'),
        ),
        migrations.AddField(
            model_name='scorecard',
            name='submission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard', to='core.Submission'),
        ),
        migrations.AddField(
            model_name='extension',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extensions', to='core.Student'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='autograders',
            field=models.ManyToManyField(blank=True, related_name='assignments', to='core.Autograder'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='core.Course'),
        ),
    ]
