# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-21 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='accepting_submissions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='autograders',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='is_published',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='max_extensions',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='scorecards_published',
        ),
    ]
