# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 19:49
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScorecardTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scorecard_template', to='core.Assignment')),
            ],
        ),
        migrations.RemoveField(
            model_name='scorecardformat',
            name='assignment',
        ),
        migrations.DeleteModel(
            name='ScorecardFormat',
        ),
    ]
