# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-02 00:11
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180224_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scorecard',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=8, primary_key=True, serialize=False),
        ),
    ]
